Feature/#18 레이아웃 수정
FinnyJakey/Podo-Market pull request #19
Opened 2023-11-08 08:26 UTC by kgunwoo26

### 상세 내용
- 메인 액티비티 시작 화면 변경
- 필터링 체크버튼 추가
- 로그아웃 버튼 추가

2023-11-08 11:31 UTC, FinnyJakey requested changes
어제 말했던 내용 중에 찜(하트) 기능도 제외하자는 걸로 의견이 모였던 것 같은데 이 부분도 제거가 된 걸로 보이는데 명시가 안 되어 있어요! 그리고 .idea 폴더 (Unresolved Version files?)는 제외해주십쇼 ㅠ.ㅠ

2023-11-08 11:34 UTC, kgunwoo26 commented
> 어제 말했던 내용 중에 찜(하트) 기능도 제외하자는 걸로 의견이 모였던 것 같은데 이 부분도 제거가 된 걸로 보이는데 명시가 안 되어 있어요! 그리고 .idea 폴더 (Unresolved Version files?)는 제외해주십쇼 ㅠ.ㅠ

제외한다고 했는데 제외가 안됐나보네요 ㅠㅠ 이따가 들어가서 수정해서 다시 올리겠습니다 ! 상세내용에 좋아요 버튼 제거 추가했습니다.

2023-11-08 11:39 UTC, jisu-0305 reviewed
.idea폴더안에 있는 항목들도 gitadd되서 merge가 안되는데 제외시켜주실 수 있나요? app내의 내용이 아닌 것 같아서요

2023-11-08 11:39 UTC, jisu-0305 commented on .idea/.name
![merge오류2](https://github.com/FinnyJakey/Podo-Market/assets/120697456/6fa8a5de-42a5-40cf-bcc3-d6417f7d8cba)


.idea폴더안에 있는 항목들도 gitadd되서 merge가 안되는데 제외시켜주실 수 있나요? app내의 내용이 아닌 것 같아서요

2023-11-08 15:42 UTC, FinnyJakey approved these changes
LGTM

2023-11-09 05:08 UTC, jisu-0305 approved these changes
LGTM

2023-11-09 06:04 UTC, merged